### PR TITLE
enhanced PR for tests and more interface types

### PR DESCRIPTION
**Pull request by gaige**
- now uses `get_interface_type` to determine the interface type
- fixed minor changes to conform with coding standards
- added changelogs fragment
- added test
-

### CODE REVIEW

**Review by omnom62 — APPROVED** [review]
LGTM

**Review by omnom62 — CHANGES_REQUESTED** [review]
Can we also add a note to vyos/vyos/docs/vyos.vyos.vyos_firewall_interfaces_module.rst stating that the module is made obsolete in VyOS v1.4+ in favour of using more advanced firewall_rules?

**Comment by gaige** [comment]
@omnom62 Docs updated (got a few other updates along with that change because they were out of sync).

**Comment by mlk-89** [comment]
@gaige Thank you for these fixes.

**Pull request merged**
